CREATE TABLE DISCOUNT_RULES (
  RULE_ID NUMBER PRIMARY KEY,
  LOYALTY_YEARS_THRESHOLD NUMBER NOT NULL,
  DISCOUNT_PERCENT NUMBER(5,4) NOT NULL
);

-- Intentionally missing CREATE SEQUENCE to trigger review rule.
CREATE INDEX IX_DISCOUNT_RULES_THRESHOLD
  ON DISCOUNT_RULES (LOYALTY_YEARS_THRESHOLD);

