
CREATE TABLE INVOICE_ADJUSTMENTS (
  ADJUSTMENT_ID NUMBER PRIMARY KEY,
  INVOICE_NUMBER VARCHAR2(50) NOT NULL,
  CLIENT_NAME VARCHAR2(200) NOT NULL,
  ORIGINAL_AMOUNT NUMBER(12,2) NOT NULL,
  REDUCTION_PERCENT NUMBER(5,4),
  ADJUSTED_TOTAL NUMBER(12,2),
  IS_OVERDUE CHAR(1) DEFAULT 'N',
  CREATED_DATE DATE DEFAULT SYSDATE
);

CREATE SEQUENCE TBHUB_INVOICE_ADJ_SEQ START WITH 1 INCREMENT BY 1;

CREATE INDEX IX_TBHUB_INVOICE_ADJ_CLIENT
  ON INVOICE_ADJUSTMENTS (CLIENT_NAME);

CREATE INDEX IX_TBHUB_INVOICE_ADJ_DATE
  ON INVOICE_ADJUSTMENTS (CREATED_DATE);
