-- Developer: CodeReviewAgentPOC

CREATE TABLE TBHUB_PREMIUM_RATES (
  RATE_ID NUMBER PRIMARY KEY,
  AGE_LOADING_THRESHOLD NUMBER NOT NULL,
  LOADING_PERCENT NUMBER(5,4) NOT NULL,
  TAX_RATE NUMBER(5,4) NOT NULL
);

CREATE SEQUENCE TBHUB_PREMIUM_RATES_SEQ START WITH 1 INCREMENT BY 1;

CREATE INDEX IX_TBHUB_PREMIUM_RATES_THRESHOLD
  ON TBHUB_PREMIUM_RATES (AGE_LOADING_THRESHOLD);

