-- Developer: CodeReviewAgentPOC

CREATE TABLE TBHUB_DISCOUNT_RULES (
  RULE_ID NUMBER PRIMARY KEY,
  LOYALTY_YEARS_THRESHOLD NUMBER NOT NULL,
  DISCOUNT_PERCENT NUMBER(5,4) NOT NULL
);

CREATE SEQUENCE TBHUB_DISCOUNT_RULES_SEQ START WITH 1 INCREMENT BY 1;

CREATE INDEX IX_TBHUB_DISCOUNT_RULES_THRESHOLD
  ON TBHUB_DISCOUNT_RULES (LOYALTY_YEARS_THRESHOLD);

