-- No developer header here on purpose (rule violation)

CREATE TABLE CUSTOMER (
  CUSTOMER_ID NUMBER PRIMARY KEY,
  NAME VARCHAR2(100) NOT NULL
);

CREATE OR REPLACE PROCEDURE PROC_CREATE_CUSTOMER(p_name IN VARCHAR2) AS
BEGIN
  NULL;
END;
/

CREATE OR REPLACE PACKAGE PKG_CUSTOMER AS
  PROCEDURE DO_SOMETHING;
END;
/

CREATE OR REPLACE FUNCTION FN_CUSTOMER_COUNT RETURN NUMBER AS
BEGIN
  RETURN 0;
END;
/

