-- Developer: Rex
-- Description: Create renewal tracking table

CREATE TABLE RENEWAL_TRACKING (
    RENEWAL_ID NUMBER PRIMARY KEY,
    POLICY_NUMBER VARCHAR2(50) NOT NULL,
    CUSTOMER_AGE NUMBER NOT NULL,
    BASE_PREMIUM NUMBER(10,2) NOT NULL,
    FINAL_PREMIUM NUMBER(10,2),
    RENEWAL_DATE DATE DEFAULT SYSDATE,
    STATUS VARCHAR2(20) DEFAULT 'PENDING'
);

CREATE INDEX IDX_RENEWAL_POLICY ON RENEWAL_TRACKING (POLICY_NUMBER);

CREATE SEQUENCE SEQ_RENEWAL_ID START WITH 1 INCREMENT BY 1;
