-- Developer: Dev Y

-- Violations:
-- - No Jira key in filename
-- - DB objects do not follow required prefixes

CREATE OR REPLACE PROCEDURE CREATE_CUSTOMER(p_name IN VARCHAR2) AS
BEGIN
  NULL;
END;
/

CREATE OR REPLACE PACKAGE CUSTOMER_PKG AS
  PROCEDURE DO_SOMETHING;
END;
/

CREATE OR REPLACE FUNCTION CUSTOMER_COUNT RETURN NUMBER AS
BEGIN
  RETURN 0;
END;
/

